/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "tertiary": "#51605a",
        "surface-tint": "#3f4cda",
        "background": "#faf9fd",
        "surface-container-highest": "#e3e2e6",
        "surface-high": "#e9e7eb",
        "inverse-primary": "#bec2ff",
        "on-surface-variant": "#454655",
        "primary-fixed-dim": "#bec2ff",
        "on-error": "#ffffff",
        "outline": "#767686",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-dim": "#dbd9dd",
        "secondary-container": "#79f7b8",
        "surface": "#faf9fd",
        "secondary-fixed": "#7cfabb",
        "secondary-fixed-dim": "#5edda0",
        "tertiary-fixed-dim": "#bacac3",
        "on-surface": "#1a1b1e",
        "on-secondary-container": "#007149",
        "surface-container-high": "#e9e7eb",
        "surface-low": "#f4f3f7",
        "tertiary-container": "#697973",
        "on-primary-container": "#fffdff",
        "on-secondary-fixed-variant": "#005234",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#3b4a44",
        "on-background": "#1a1b1e",
        "outline-variant": "#c6c5d7",
        "error": "#ba1a1a",
        "primary": "#3d4ad8",
        "tertiary-fixed": "#d5e6df",
        "on-secondary-fixed": "#002112",
        "online-indicator": "#2eb67d",
        "primary-container": "#5865f2",
        "on-primary-fixed": "#000569",
        "surface-variant": "#e3e2e6",
        "on-tertiary": "#ffffff",
        "surface-container": "#efedf1",
        "on-primary-fixed-variant": "#222fc2",
        "surface-bright": "#faf9fd",
        "surface-container-low": "#f4f3f7",
        "unread-badge": "#5865f2",
        "on-tertiary-container": "#fbfffb",
        "inverse-surface": "#2f3033",
        "primary-fixed": "#e0e0ff",
        "inverse-on-surface": "#f1f0f4",
        "secondary": "#006c46",
        "on-tertiary-fixed": "#101e1a",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "section-padding": "24px",
        "list-item-padding": "12px",
        "message-gap": "4px",
        "container-margin": "16px",
        "stack-gap": "8px",
        "story-gap": "12px"
      },
      "fontFamily": {
        "headline-md": ["Inter"],
        "badge": ["Inter"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-lg": ["Inter"]
      },
      "fontSize": {
        "headline-md": ["20px", {"lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "badge": ["10px", {"lineHeight": "1", "fontWeight": "700"}],
        "label-sm": ["11px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-lg": ["13px", {"lineHeight": "18px", "letterSpacing": "0.01em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
